### PR TITLE
RUMM-1824: Fix dependency check task crash in the multi-module setup

### LINKED ISSUE #62: Execution failed for task 'checkSdkDeps'
Hi all. 

We have a problem with applying Datadog Gradle plugin `com.datadoghq:dd-sdk-android-gradle-plugin:1.2.0`.

When the plugin is applied in the app's build.gradle script with `id("com.datadoghq.dd-sdk-android-gradle-plugin"), we get the following error when we run a build(assemble task).

We have two flavors: production and staging.
Both flavors have debug and release variants.
We have the app module that include several other modules as dependencies.

**Additional context**
 - Android Build Tools version: 4.1.3
 - Gradle version: 7.3.1
 - OS version: Mac OS Big Sur 11.4
 - Plugin version: 1.2.0

Stacktrace: 
`Execution failed for task ':app:checkSdkDepsStagingDebug'.
> Error while evaluating property 'configuration' of task ':app:checkSdkDepsStagingDebug'
   > Could not resolve all files for configuration ':app:stagingDebugCompileClasspath'.
      > The consumer was configured to find an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm'. However we cannot choose between the following variants of project :features:
          - Configuration ':features:stagingDebugApiElements' variant android-databinding-class-log declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-databinding-class-log' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
          - Configuration ':features:stagingDebugApiElements' variant android-manifest declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-manifest' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
          - Configuration ':features:stagingDebugApiElements' variant android-renderscript declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-renderscript' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
          - Configuration ':features:stagingDebugApiElements' variant android-symbol-with-package-name declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-symbol-with-package-name' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
      > The consumer was configured to find an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm'. However we cannot choose between the following variants of project :features:splash:
          - Configuration ':features:splash:stagingDebugApiElements' variant android-databinding-class-log declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-databinding-class-log' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
          - Configuration ':features:splash:stagingDebugApiElements' variant android-manifest declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-manifest' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
          - Configuration ':features:splash:stagingDebugApiElements' variant android-renderscript declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-renderscript' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
          - Configuration ':features:splash:stagingDebugApiElements' variant android-symbol-with-package-name declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-symbol-with-package-name' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
      > The consumer was configured to find an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm'. However we cannot choose between the following variants of project :features:auth:
          - Configuration ':features:auth:stagingDebugApiElements' variant android-databinding-class-log declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-databinding-class-log' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
          - Configuration ':features:auth:stagingDebugApiElements' variant android-manifest declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-manifest' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
          - Configuration ':features:auth:stagingDebugApiElements' variant android-renderscript declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-renderscript' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
          - Configuration ':features:auth:stagingDebugApiElements' variant android-symbol-with-package-name declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-symbol-with-package-name' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
      > The consumer was configured to find an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm'. However we cannot choose between the following variants of project :features:scanner:
          - Configuration ':features:scanner:stagingDebugApiElements' variant android-databinding-class-log declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-databinding-class-log' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
          - Configuration ':features:scanner:stagingDebugApiElements' variant android-manifest declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-manifest' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
          - Configuration ':features:scanner:stagingDebugApiElements' variant android-renderscript declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-renderscript' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
          - Configuration ':features:scanner:stagingDebugApiElements' variant android-symbol-with-package-name declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-symbol-with-package-name' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
      > The consumer was configured to find an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm'. However we cannot choose between the following variants of project :features:home:
          - Configuration ':features:home:stagingDebugApiElements' variant android-databinding-class-log declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-databinding-class-log' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
          - Configuration ':features:home:stagingDebugApiElements' variant android-manifest declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-manifest' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
          - Configuration ':features:home:stagingDebugApiElements' variant android-renderscript declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-renderscript' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
          - Configuration ':features:home:stagingDebugApiElements' variant android-symbol-with-package-name declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-symbol-with-package-name' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
      > The consumer was configured to find an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm'. However we cannot choose between the following variants of project :features:payment:
          - Configuration ':features:payment:stagingDebugApiElements' variant android-databinding-class-log declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-databinding-class-log' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
          - Configuration ':features:payment:stagingDebugApiElements' variant android-manifest declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-manifest' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
          - Configuration ':features:payment:stagingDebugApiElements' variant android-renderscript declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-renderscript' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
          - Configuration ':features:payment:stagingDebugApiElements' variant android-symbol-with-package-name declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-symbol-with-package-name' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
      > The consumer was configured to find an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm'. However we cannot choose between the following variants of project :features:editor:
          - Configuration ':features:editor:stagingDebugApiElements' variant android-databinding-class-log declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-databinding-class-log' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
          - Configuration ':features:editor:stagingDebugApiElements' variant android-manifest declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-manifest' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
          - Configuration ':features:editor:stagingDebugApiElements' variant android-renderscript declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-renderscript' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
          - Configuration ':features:editor:stagingDebugApiElements' variant android-symbol-with-package-name declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-symbol-with-package-name' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
      > The consumer was configured to find an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm'. However we cannot choose between the following variants of project :features:widget:
          - Configuration ':features:widget:stagingDebugApiElements' variant android-databinding-class-log declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-databinding-class-log' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
          - Configuration ':features:widget:stagingDebugApiElements' variant android-manifest declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-manifest' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
          - Configuration ':features:widget:stagingDebugApiElements' variant android-renderscript declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-renderscript' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
          - Configuration ':features:widget:stagingDebugApiElements' variant android-symbol-with-package-name declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-symbol-with-package-name' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
      > The consumer was configured to find an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm'. However we cannot choose between the following variants of project :common:core:
          - Configuration ':common:core:stagingDebugApiElements' variant android-databinding-class-log declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-databinding-class-log' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
          - Configuration ':common:core:stagingDebugApiElements' variant android-manifest declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-manifest' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
          - Configuration ':common:core:stagingDebugApiElements' variant android-renderscript declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-renderscript' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
          - Configuration ':common:core:stagingDebugApiElements' variant android-symbol-with-package-name declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-symbol-with-package-name' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
      > The consumer was configured to find an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm'. However we cannot choose between the following variants of project :common:workflow:
          - Configuration ':common:workflow:stagingDebugApiElements' variant android-databinding-class-log declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-databinding-class-log' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
          - Configuration ':common:workflow:stagingDebugApiElements' variant android-manifest declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-manifest' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
          - Configuration ':common:workflow:stagingDebugApiElements' variant android-renderscript declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-renderscript' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
          - Configuration ':common:workflow:stagingDebugApiElements' variant android-symbol-with-package-name declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-symbol-with-package-name' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
      > The consumer was configured to find an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm'. However we cannot choose between the following variants of project :common:core-ui:
          - Configuration ':common:core-ui:stagingDebugApiElements' variant android-databinding-class-log declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-databinding-class-log' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
          - Configuration ':common:core-ui:stagingDebugApiElements' variant android-manifest declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-manifest' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
          - Configuration ':common:core-ui:stagingDebugApiElements' variant android-renderscript declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-renderscript' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
          - Configuration ':common:core-ui:stagingDebugApiElements' variant android-symbol-with-package-name declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-symbol-with-package-name' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it`

### PR DESCRIPTION
**Pull request by 0xnm**
### What does this PR do?

Fixes #62. The problem comes in the multi-module setup, when there is module `A` with some flavors (say `foo` and `bar`) which is using another module `B` without mentioned flavors.

Because the way task execution works, gradle tries to unwrap `Configuration` input, but it fails to do that, because there is no 1:1 match between `A` and `B` configurations (but AGP itself is able to match them, because it applies fallback).

This change proposes to use configuration name instead in the input, so that it can be later pulled from the configurations list (using `project` in the task is not compatible with configuration cache, but using `Configuration` in the input is not compatible as well, so we don't break anything from this point).

Because now inputs don't change if configuration itself is changed, task is cached more aggressively (it can be skipped 2nd time, even if dependency tree has changed), we will leverage task outputs to control if task can be cached or not. This has an edge case: if there was successful execution with DD dependency in the tree and then DD dependency was removed, then task won't be executed, but I think we can allow that.

Other options considered:

1. Try to resolve configuration at the task creation step - most probably will fail (because AGP didn't apply fallbacks yet), and resolving configuration at the script configuration step is not nice.
2.  Use variant compilation outputs as task input - will solve caching issue, but that will postpone the check even further in the task execution graph (and these outputs will most of the time different if output contains some code-generated timestamp, build number, etc., making the task non-incremental essentially).
Also this change bumps version to `1.2.1`, because I think it is worth to do patch release.

Additional read:

https://docs.gradle.org/current/userguide/more_about_tasks.html
https://docs.gradle.org/current/userguide/custom_tasks.html

### Review checklist (to be filled by reviewers)

- [x] Feature or bugfix MUST have appropriate tests (unit, integration, e2e)
- [x] Make sure you discussed the feature or bugfix with the maintaining team in an Issue
- [x] Make sure each commit and the PR mention the Issue number (cf the [CONTRIBUTING](CONTRIBUTING.md) doc)

### CODE REVIEW

**Review by xgouchet — APPROVED** [review]

File: dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdCheckSdkDepsTask.kt [hunk 1]
```diff
@@ -68,6 +101,8 @@ abstract class DdCheckSdkDepsTask :
                     )
                 }
             }
+        } else {
+            isLastRunSuccessful = true
```
Comment (mariusc83) [inline dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdCheckSdkDepsTask.kt:105]: What happens if the task succeeded and in the meantime I change my dependencies and remove Datadog dependency from there. This task would still be considered as `up-to-date` not ?

**Review by mariusc83 — CHANGES_REQUESTED** [review]

File: dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdCheckSdkDepsTask.kt (hunk 1 above)
Comment (0xnm) [reply dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdCheckSdkDepsTask.kt:105]: Yes, I mentioned it in the PR description. This is an edge case which cannot be solved with current inputs.

**Review by mariusc83 — APPROVED** [review]
