### PR TITLE
RUMM-1451: Support Gradle configuration cache

### LINKED ISSUE #39: Gradle plugin doesn't work with Gradle Configuration Cache (7.x)
There is a new feature in Gradle, the configuration cache. The goal is not to execute the config step every time, it can be cached if the plugins support this.
We want to enable this feature, it would save us time, and especially these hot summer days, it's a double win for laptop users (hot machine->slowew build->even hotter->even slower).

The build fails with the current version of the dd-gradle-plugin when we enable this new Gradle feature by adding **org.gradle.unsafe.configuration-cache=true** to **gradle.properties**

Datadog gradle plugin 1.0.1
Gradle 7.1

Documentation: https://docs.gradle.org/current/userguide/configuration_cache.html

1: Task failed with an exception.
-----------
```
* What went wrong:
Configuration cache state could not be cached: field 'actions' from type 'org.gradle.api.DefaultTask': error writing value of type 'java.util.ArrayList'
> Configuration cache state could not be cached: field 'action' from type 'org.gradle.api.internal.AbstractTask$TaskActionWrapper': error writing value of type 'com.datadog.gradle.plugin.DdAndroidGradlePlugin$configureVariantForSdkCheck$1'
   > Configuration cache state could not be cached: field '$variant' from type 'com.datadog.gradle.plugin.DdAndroidGradlePlugin$configureVariantForSdkCheck$1': error writing value of type 'com.android.build.gradle.internal.api.ApplicationVariantImpl'
   > Configuration cache state could not be cached: field 'unitTestVariant' from type 'com.android.build.gradle.internal.api.ApplicationVariantImpl': error writing value of type 'com.android.build.gradle.internal.api.UnitTestVariantImpl'
   > Configuration cache state could not be cached: field 'variantData' from type 'com.android.build.gradle.internal.api.UnitTestVariantImpl': error writing value of type 'com.android.build.gradle.internal.variant.TestVariantData'
   > Configuration cache state could not be cached: field 'testedVariantData' from type 'com.android.build.gradle.internal.variant.TestVariantData': error writing value of type 'com.android.build.gradle.internal.variant.ApplicationVariantData'
   > Configuration cache state could not be cached: field 'globalScope' from type 'com.android.build.gradle.internal.variant.ApplicationVariantData': error writing value of type 'com.android.build.gradle.internal.scope.GlobalScope'
   > Configuration cache state could not be cached: field 'extension' from type 'com.android.build.gradle.internal.scope.GlobalScope': error writing value of type 'com.android.build.gradle.internal.dsl.BaseAppModuleExtension'
   > Configuration cache state could not be cached: field 'publicExtensionImpl' from type 'com.android.build.gradle.internal.dsl.BaseAppModuleExtension': error writing value of type 'com.android.build.gradle.internal.dsl.ApplicationExtensionImpl$AgpDecorated'
   > Configuration cache state could not be cached: field 'buildTypes' from type 'com.android.build.gradle.internal.dsl.ApplicationExtensionImpl$AgpDecorated': error writing value of type 'org.gradle.api.internal.FactoryNamedDomainObjectContainer'
   > Configuration cache state could not be cached: field 'eventRegister' from type 'org.gradle.api.internal.FactoryNamedDomainObjectContainer': error writing value of type 'org.gradle.api.internal.collections.DefaultCollectionEventRegister'
   > Configuration cache state could not be cached: field 'addActions' from type 'org.gradle.api.internal.collections.DefaultCollectionEventRegister': error writing value of type 'org.gradle.internal.ImmutableActionSet$SetWithFewActions'
   > Configuration cache state could not be cached: field 'actions' from type 'org.gradle.internal.ImmutableActionSet$SetWithFewActions': error writing value of type '[Lorg.gradle.api.Action;'
   > Configuration cache state could not be cached: field 'delegate' from type 'org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction': error writing value of type 'org.gradle.configuration.internal.DefaultUserCodeApplicationContext$CurrentApplication$1'
   > Configuration cache state could not be cached: field 'val$action' from type 'org.gradle.configuration.internal.DefaultUserCodeApplicationContext$CurrentApplication$1': error writing value of type 'com.android.build.gradle.internal.variant.LegacyVariantInputManager$3'
   > Configuration cache state could not be cached: field '$tmp0' from type 'com.android.build.gradle.internal.variant.LegacyVariantInputManager$3': error writing value of type 'com.android.build.gradle.internal.variant.LegacyVariantInputManager'
   > Configuration cache state could not be cached: field 'sourceSetManager' from type 'com.android.build.gradle.internal.variant.LegacyVariantInputManager': error writing value of type 'com.android.build.gradle.internal.dependency.SourceSetManager'
   > Configuration cache state could not be cached: field 'sourceSetsContainer' from type 'com.android.build.gradle.internal.dependency.SourceSetManager': error writing value of type 'org.gradle.api.internal.FactoryNamedDomainObjectContainer'
   > Configuration cache state could not be cached: field 'eventRegister' from type 'org.gradle.api.internal.FactoryNamedDomainObjectContainer': error writing value of type 'org.gradle.api.internal.collections.DefaultCollectionEventRegister'
   > Configuration cache state could not be cached: field 'addActions' from type 'org.gradle.api.internal.collections.DefaultCollectionEventRegister': error writing value of type 'org.gradle.internal.ImmutableActionSet$SetWithFewActions'
   > Configuration cache state could not be cached: field 'actions' from type 'org.gradle.internal.ImmutableActionSet$SetWithFewActions': error writing value of type '[Lorg.gradle.api.Action;'
   > Configuration cache state could not be cached: field 'delegate' from type 'org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction': error writing value of type 'org.gradle.configuration.internal.DefaultUserCodeApplicationContext$CurrentApplication$1'
   > Configuration cache state could not be cached: field 'val$action' from type 'org.gradle.configuration.internal.DefaultUserCodeApplicationContext$CurrentApplication$1': error writing value of type 'org.jetbrains.kotlin.gradle.plugin.mpp.SyncKotlinAndAndroidSourceSetsKt$syncKotlinAndAndroidSourceSets$1'
   > Configuration cache state could not be cached: field '$target' from type 'org.jetbrains.kotlin.gradle.plugin.mpp.SyncKotlinAndAndroidSourceSetsKt$syncKotlinAndAndroidSourceSets$1': error writing value of type 'org.jetbrains.kotlin.gradle.plugin.mpp.KotlinAndroidTarget'
   > Configuration cache state could not be cached: field 'kotlinComponents$delegate' from type 'org.jetbrains.kotlin.gradle.plugin.mpp.KotlinAndroidTarget': error writing value of type 'kotlin.SynchronizedLazyImpl'
   > KotlinJvmAndroidCompilation with name 'main' not found.
```

### PR DESCRIPTION
**Pull request by 0xnm**
### What does this PR do?

This change adds support of configuration cache. Currently, if we run task with `--configuration-cache` flag, the following errors happen claiming it cannot serialize task:

1. Execution of upload task:

```
value NativePRNG failed Java Object Serialization
field secureRandom of sun.security.ssl.SSLContextImpl$TLSContext
bean of type sun.security.ssl.SSLContextImpl$TLSContext
field context of sun.security.ssl.SSLSocketFactoryImpl
bean of type sun.security.ssl.SSLSocketFactoryImpl
field sslSocketFactory of okhttp3.OkHttpClient
bean of type okhttp3.OkHttpClient
field client of com.datadog.gradle.plugin.internal.OkHttpUploader
bean of type com.datadog.gradle.plugin.internal.OkHttpUploader
field uploader of com.datadog.gradle.plugin.DdMappingFileUploadTasktask:samples:variants:uploadMappingFullRedRelease of type com.datadog.gradle.plugin.DdMappingFileUploadTask
```

This happens because of the OkHttp client, which is not actually needed during the serialization, so we can remove it from serialization by removing backing field from `client`. Simply adding `@Transient` doesn't work, because on deserialization we get `null`. This non-obvious issue is described in the following ticket https://youtrack.jetbrains.com/issue/KT-23998.

Also we have to remove usages of `project.exec` and replace it with `ExecOperations`. `ExecOperations` is incubating as of Gradle 6.8.3, but it is available since Gradle 6.1 and was de-incubated with Gradle 7 https://github.com/gradle/gradle/pull/15574.

2. Execution of SDK library check task (which is linked to the compilation task): see in #39. This happens because `Configuration` access from task level is not supported by configuration cache. And the necessary API to access it in the lazy way is missing: see https://github.com/gradle/gradle/issues/12871 and https://issuetracker.google.com/issues/162074215. For now we will just skip configuration access if plugin configuration has sdk check level set to `none` to allow using configuration cache for experienced users.

Apart of the issues above related purely to the configuration cache, this change also does the following:

1. Makes Android Gradle plugin `compileOnly`, so that it is not included in the final artifact. Since our plugin is supposed to be used with Android Gradle plugin being in the classpath, it is safe thing to do, and having version `4.1.2` included in the artifact was causing issues when newer Android Gradle Plugin exists in classpath as well.
2. Newer versions of Android Gradle plugin don't have `org.json` in transitive dependencies, so it was expicitly added to the list of dependencies.
3. Upload task will never be `up-to-date` now so that it can be always executed. Because it could be cached before even if network request failed.

Fixes #39.

### Review checklist (to be filled by reviewers)

- [x] Feature or bugfix MUST have appropriate tests (unit, integration, e2e)
- [x] Make sure you discussed the feature or bugfix with the maintaining team in an Issue
- [x] Make sure each commit and the PR mention the Issue number (cf the [CONTRIBUTING](CONTRIBUTING.md) doc)

### CODE REVIEW

File: dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePlugin.kt [hunk 1]
```diff
@@ -158,8 +160,11 @@ class DdAndroidGradlePlugin : Plugin<Project> {
                         SdkCheckLevel.WARN -> {
                             LOGGER.warn(MISSING_DD_SDK_MESSAGE.format(variant.name))
                         }
-                        SdkCheckLevel.NONE -> {
-                            // no-op, ignore that and make compiler happy
+                        else -> {
```
Comment (xgouchet) [inline dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePlugin.kt:163]: Has the `SdkCheckLevel.NONE` value been removed ?

**Review by xgouchet — APPROVED** [review]

File: dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePlugin.kt (hunk 1 above)
Comment (0xnm) [reply dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePlugin.kt:163]: No, check for `.NONE` was moved out of lambda, before action creation. So it cannot be here logically, but it should be some branch to make compiler happy.

**Comment by 0xnm** [comment]
@xgouchet I had to update this PR after testing all the tasks with latest Gradle `7.1` and latest AGP `7.1.0-alpha02`. I updated description of this PR to reflect the changes. Can you please review it again?

**Review by xgouchet — APPROVED** [review]

**Review by mariusc83 — APPROVED** [review]
